/* The following code was generated by JFlex 1.4.3 on 6/03/22 17:05 */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 6/03/22 17:05 from the specification file
 * <tt>C:/Users/pinto/OneDrive/Documentos/NetBeansProjects/Pregunta6Analizador/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\40\2\0\1\6\22\0\1\6\1\42\4\0\1\45"+
    "\1\0\1\51\1\52\1\47\1\4\1\10\1\2\1\5\1\37\12\3"+
    "\1\0\1\50\1\43\1\41\1\44\2\0\32\1\4\0\1\1\1\0"+
    "\1\17\1\23\1\35\1\26\1\24\1\14\1\22\1\32\1\11\1\1"+
    "\1\25\1\15\1\33\1\12\1\16\1\34\1\1\1\21\1\20\1\13"+
    "\1\27\1\30\1\36\1\1\1\31\1\1\1\7\1\46\1\7\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\0"+
    "\1\6\13\1\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\2\0\1\20\1\3\5\0\1\1"+
    "\1\21\22\1\1\6\1\22\1\23\1\24\1\25\2\0"+
    "\1\20\1\0\1\3\1\26\16\1\3\0\1\20\1\3"+
    "\1\0\1\26\7\1\4\0\1\3\2\0\4\1\3\0"+
    "\1\20\2\0\1\1\6\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\u012d"+
    "\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a\0\u0285"+
    "\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387\0\u03b2\0\u03dd"+
    "\0\u0408\0\327\0\327\0\327\0\327\0\u0433\0\u045e\0\u0489"+
    "\0\u04b4\0\u04df\0\u050a\0\u0535\0\u0560\0\u058b\0\u05b6\0\53"+
    "\0\u05e1\0\u060c\0\u0637\0\u0662\0\u068d\0\u06b8\0\u06e3\0\u070e"+
    "\0\u0739\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u083b\0\u0866"+
    "\0\u0891\0\u08bc\0\u08e7\0\327\0\327\0\327\0\327\0\u0912"+
    "\0\u093d\0\u0968\0\u0993\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a"+
    "\0\u0a95\0\u0ac0\0\u0aeb\0\u0b16\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2"+
    "\0\u0bed\0\u0c18\0\u0c43\0\u0c6e\0\u0c99\0\u0cc4\0\u0cef\0\u0d1a"+
    "\0\u0d45\0\u0d70\0\u0d9b\0\u0dc6\0\u0df1\0\u0e1c\0\u0e47\0\u0e72"+
    "\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e\0\u0f49\0\327\0\u0f74\0\u0f9f"+
    "\0\u0fca\0\u0ff5\0\u1020\0\u104b\0\u1076\0\u10a1\0\u10cc\0\327"+
    "\0\u10f7\0\u1122\0\u114d\0\u1178\0\u11a3\0\u11ce\0\u11f9\0\u1224"+
    "\0\u124f";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\2\2\1\13\1\14\2\2\1\15\2\2"+
    "\1\16\1\17\1\2\1\20\1\2\1\21\3\2\1\22"+
    "\1\23\1\24\1\25\1\7\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\10\1\0\1\2"+
    "\1\0\1\2\1\37\4\0\26\2\17\0\1\40\52\0"+
    "\1\41\1\42\1\43\50\0\1\4\130\0\1\7\1\0"+
    "\1\7\27\0\1\7\13\0\1\44\1\0\1\45\1\46"+
    "\2\0\2\10\26\44\12\0\2\10\1\0\1\44\1\0"+
    "\1\45\1\46\1\0\1\7\1\10\1\11\26\44\1\0"+
    "\1\7\10\0\2\10\1\0\1\2\1\0\1\2\1\37"+
    "\4\0\1\2\1\47\1\2\1\50\16\2\1\51\3\2"+
    "\15\0\1\2\1\0\1\2\1\37\4\0\4\2\1\52"+
    "\1\53\20\2\15\0\1\2\1\0\1\2\1\37\4\0"+
    "\5\2\1\54\20\2\15\0\1\2\1\0\1\2\1\37"+
    "\4\0\2\2\1\55\16\2\1\56\3\2\1\57\15\0"+
    "\1\2\1\0\1\2\1\37\4\0\5\2\1\60\2\2"+
    "\1\61\7\2\1\62\5\2\15\0\1\2\1\0\1\2"+
    "\1\37\4\0\4\2\1\63\21\2\15\0\1\2\1\0"+
    "\1\2\1\37\4\0\5\2\1\50\5\2\1\64\12\2"+
    "\15\0\1\2\1\0\1\2\1\37\4\0\5\2\1\65"+
    "\20\2\15\0\1\2\1\0\1\2\1\37\4\0\10\2"+
    "\1\66\5\2\1\67\7\2\15\0\1\2\1\0\1\2"+
    "\1\37\4\0\4\2\1\70\1\2\1\63\12\2\1\71"+
    "\4\2\15\0\1\2\1\0\1\2\1\37\4\0\21\2"+
    "\1\72\4\2\53\0\1\73\54\0\1\74\52\0\1\75"+
    "\52\0\1\76\52\0\1\77\12\0\1\44\1\100\1\45"+
    "\1\46\2\0\2\10\26\44\12\0\2\10\3\0\1\2"+
    "\51\0\1\101\1\102\1\0\1\103\50\0\1\41\1\42"+
    "\51\0\1\41\52\0\1\104\50\0\1\44\5\0\2\105"+
    "\26\44\12\0\2\105\3\0\1\45\1\46\2\0\2\105"+
    "\40\0\2\105\3\0\1\45\50\0\1\2\1\0\1\2"+
    "\1\37\4\0\2\2\1\50\23\2\15\0\1\2\1\0"+
    "\1\2\1\37\4\0\23\2\1\56\2\2\15\0\1\2"+
    "\1\0\1\2\1\37\4\0\5\2\1\106\20\2\15\0"+
    "\1\2\1\0\1\2\1\37\4\0\10\2\1\50\15\2"+
    "\15\0\1\2\1\0\1\2\1\37\4\0\1\2\1\107"+
    "\24\2\15\0\1\2\1\0\1\2\1\37\4\0\10\2"+
    "\1\110\15\2\15\0\1\2\1\0\1\2\1\37\4\0"+
    "\5\2\1\111\20\2\15\0\1\2\1\0\1\2\1\37"+
    "\4\0\1\112\25\2\15\0\1\2\1\0\1\2\1\37"+
    "\4\0\5\2\1\113\20\2\15\0\1\2\1\0\1\2"+
    "\1\37\4\0\13\2\1\114\12\2\15\0\1\2\1\0"+
    "\1\2\1\37\4\0\2\2\1\115\23\2\15\0\1\2"+
    "\1\0\1\2\1\37\4\0\7\2\1\115\16\2\15\0"+
    "\1\2\1\0\1\2\1\37\4\0\3\2\1\116\22\2"+
    "\15\0\1\2\1\0\1\2\1\37\4\0\1\117\25\2"+
    "\15\0\1\2\1\0\1\2\1\37\4\0\1\120\25\2"+
    "\15\0\1\2\1\0\1\2\1\37\4\0\12\2\1\121"+
    "\13\2\15\0\1\2\1\0\1\2\1\37\4\0\6\2"+
    "\1\122\17\2\15\0\1\2\1\0\1\2\1\37\4\0"+
    "\6\2\1\53\17\2\15\0\1\2\1\0\1\2\1\37"+
    "\4\0\1\123\25\2\14\0\40\73\1\0\12\73\2\0"+
    "\1\124\1\125\1\126\51\0\1\102\51\0\1\101\1\102"+
    "\52\0\1\127\52\0\1\130\1\131\55\0\2\132\40\0"+
    "\2\132\1\0\1\2\1\0\1\2\1\37\4\0\6\2"+
    "\1\47\17\2\15\0\1\2\1\0\1\2\1\37\4\0"+
    "\11\2\1\50\14\2\15\0\1\2\1\0\1\2\1\37"+
    "\4\0\1\54\25\2\15\0\1\2\1\0\1\2\1\37"+
    "\4\0\10\2\1\47\15\2\15\0\1\2\1\0\1\2"+
    "\1\37\4\0\2\2\1\133\23\2\15\0\1\2\1\0"+
    "\1\2\1\37\4\0\4\2\1\134\21\2\15\0\1\2"+
    "\1\0\1\2\1\37\4\0\6\2\1\135\17\2\15\0"+
    "\1\2\1\0\1\2\1\37\4\0\13\2\1\50\12\2"+
    "\15\0\1\2\1\0\1\2\1\37\4\0\6\2\1\136"+
    "\17\2\15\0\1\2\1\0\1\2\1\37\4\0\15\2"+
    "\1\50\10\2\15\0\1\2\1\0\1\2\1\37\4\0"+
    "\17\2\1\137\6\2\15\0\1\2\1\0\1\2\1\37"+
    "\4\0\4\2\1\140\21\2\15\0\1\2\1\0\1\2"+
    "\1\37\4\0\7\2\1\141\16\2\15\0\1\2\1\0"+
    "\1\2\1\37\4\0\4\2\1\115\21\2\17\0\1\142"+
    "\52\0\1\143\1\144\1\145\44\0\1\146\3\0\1\125"+
    "\51\0\1\147\1\127\52\0\1\130\1\131\1\43\50\0"+
    "\1\150\50\0\1\44\1\0\1\45\1\46\2\0\2\132"+
    "\26\44\12\0\2\132\1\0\1\2\1\0\1\2\1\37"+
    "\4\0\24\2\1\151\1\2\15\0\1\2\1\0\1\2"+
    "\1\37\4\0\13\2\1\152\12\2\15\0\1\2\1\0"+
    "\1\2\1\37\4\0\14\2\1\50\11\2\15\0\1\2"+
    "\1\0\1\2\1\37\4\0\16\2\1\153\7\2\15\0"+
    "\1\2\1\0\1\2\1\37\4\0\6\2\1\62\17\2"+
    "\15\0\1\2\1\0\1\2\1\37\4\0\1\154\25\2"+
    "\15\0\1\2\1\0\1\2\1\37\4\0\7\2\1\50"+
    "\16\2\16\0\1\155\1\156\1\0\1\157\44\0\1\160"+
    "\3\0\1\143\1\144\45\0\1\146\3\0\1\143\52\0"+
    "\1\161\52\0\1\162\54\0\1\43\46\0\1\2\1\0"+
    "\1\2\1\37\4\0\21\2\1\50\4\2\15\0\1\2"+
    "\1\0\1\2\1\37\4\0\6\2\1\163\17\2\15\0"+
    "\1\2\1\0\1\2\1\37\4\0\4\2\1\47\21\2"+
    "\15\0\1\2\1\0\1\2\1\37\4\0\24\2\1\50"+
    "\1\2\17\0\1\156\51\0\1\155\1\156\46\0\1\160"+
    "\3\0\1\164\52\0\1\165\1\166\45\0\1\146\5\0"+
    "\1\103\46\0\1\2\1\0\1\2\1\37\4\0\1\2"+
    "\1\50\24\2\16\0\1\167\1\164\46\0\1\160\3\0"+
    "\1\165\1\166\1\145\44\0\1\146\3\0\1\170\52\0"+
    "\1\171\54\0\1\145\52\0\1\157\45\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4730];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\4\1\1\11\1\1\1\0\21\1\4\11\2\0"+
    "\2\1\5\0\25\1\4\11\2\0\1\1\1\0\20\1"+
    "\3\0\2\1\1\0\10\1\4\0\1\11\2\0\4\1"+
    "\3\0\1\11\2\0\1\1\6\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 120) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 14: 
          { lexeme=yytext();return Multiplicacion;
          }
        case 23: break;
        case 4: 
          { lexeme=yytext();return Suma;
          }
        case 24: break;
        case 22: 
          { lexeme=yytext(); return Agrupacion;
          }
        case 25: break;
        case 15: 
          { lexeme=yytext();return Delimitador;
          }
        case 26: break;
        case 19: 
          { lexeme=yytext();return Distinto;
          }
        case 27: break;
        case 13: 
          { lexeme=yytext();return Or;
          }
        case 28: break;
        case 21: 
          { lexeme=yytext();return Mayor_Igual;
          }
        case 29: break;
        case 8: 
          { lexeme=yytext();return Igual;
          }
        case 30: break;
        case 10: 
          { lexeme=yytext();return Menor;
          }
        case 31: break;
        case 9: 
          { lexeme=yytext();return Not;
          }
        case 32: break;
        case 3: 
          { lexeme=yytext(); return Positivo;
          }
        case 33: break;
        case 12: 
          { lexeme=yytext();return And;
          }
        case 34: break;
        case 7: 
          { lexeme=yytext();return Division;
          }
        case 35: break;
        case 1: 
          { lexeme=yytext(); return Identificador;
          }
        case 36: break;
        case 11: 
          { lexeme=yytext();return Mayor;
          }
        case 37: break;
        case 20: 
          { lexeme=yytext();return Menor_Igual;
          }
        case 38: break;
        case 5: 
          { return ERROR;
          }
        case 39: break;
        case 6: 
          { /*Ignore*/
          }
        case 40: break;
        case 16: 
          { lexeme=yytext(); return Negativo;
          }
        case 41: break;
        case 2: 
          { lexeme=yytext();return Resta;
          }
        case 42: break;
        case 18: 
          { lexeme=yytext();return Comparador;
          }
        case 43: break;
        case 17: 
          { lexeme=yytext(); return Reservadas;
          }
        case 44: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
